[project]
name = "mybot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bidict>=0.23.1",
    "dishka>=1.7.2",
    "google-genai>=1.53.0",
    "openai>=2.9.0",
    "pydantic-settings>=2.12.0",
]
