[[llm_model]]
api_key = ""
base_url = ""
llm_name = "deepseek"
model_name="deepseek-reasoner"
provider_type = "openai"

[[llm_model]]
api_key = ""
base_url = ""
llm_name = "gemini"
model_name="gemini-3-pro-preview"
provider_type = "gemini"
